# VT Sim Hands --------------------------------------------------
  l_f0_j0_pos:
    type: effort_controllers/JointPositionController
    joint: l_f0_j0
    pid: {p: 100.0, i: 0.01, d: 1.0}

  l_f1_j0_pos:
    type: effort_controllers/JointPositionController
    joint: l_f1_j0
    pid: {p: 100.0, i: 0.01, d: 1.0}
