# VT Sim Hands --------------------------------------------------
  r_f0_j0_pos:
    type: effort_controllers/JointPositionController
    joint: r_f0_j0
    pid: {p: 100.0, i: 0.01, d: 1.0}

  r_f1_j0_pos:
    type: effort_controllers/JointPositionController
    joint: r_f1_j0
    pid: {p: 100.0, i: 0.01, d: 1.0}
